### PR TITLE
ROCm 4.5 merge staging into master 

### PR DESCRIPTION
**Pull request by daineAMD**

### CODE REVIEW

**Review by amcamd — APPROVED** [review]
checked master branch version bumped to 0.48.0 and rocblas >= 2.41.0

**Review by TorreZuk — APPROVED** [review]
LGTM

**Comment by daineAMD** [comment]
CI is failing due to what appears to be the rocSOLVER package not being ready. Monitoring the rocSOLVER CI [here](http://math-ci.rocm.amd.com/blue/organizations/jenkins/compute-rocm-dkms-no-npi-hipclang%2Fprecheckin%2FrocSOLVER/detail/master/60/pipeline/315) and will restart hipBLAS' CI once it has finished.

**Comment by cgmb** [comment]
> CI is failing due to what appears to be the rocSOLVER package not being ready. Monitoring the rocSOLVER CI [here](http://math-ci.rocm.amd.com/blue/organizations/jenkins/compute-rocm-dkms-no-npi-hipclang%2Fprecheckin%2FrocSOLVER/detail/master/60/pipeline/315) and will restart hipBLAS' CI once it has finished.

The ETA appears to be about 1 hour. The SLES job got started on a crippled node. It's the same one that compiled for CentOS 8 in the previous build, taking twice as long as all the others.

**Comment by daineAMD** [comment]
Thanks @cgmb for the update! I'll be out from around 6:15-7:45pm MDT, but I can restart hipBLAS CI once I'm back and merge afterwards.

**Comment by amcamd** [comment]
@daineAMD I will write the email confirming the ROCm 4.5 feature complete merge is done, and I can send the email out as late as 10pm Mountain time. Let me know when you are done, and then I will send out the email.

**Comment by cgmb** [comment]
@daineAMD. Took even longer this time, but it's done.

**Comment by amcamd** [comment]
I restarted the failing CI jobs at about 7.25 mountain time.

**Pull request merged**
