### PR TITLE
Merge yaml hotfix from develop to release-staging/rocm-rel-6.0

### PR DESCRIPTION
**Pull request by daineAMD**
`git merge --ff-only develop` into release-staging/rocm-rel-6.0. Really only need b875c52 but thought this ff merge would be cleaner since other changes are mainly just CI updates.

### CODE REVIEW

**Review by TorreZuk — APPROVED** [review]
LGTM.  Yes I would ffwd as long as you are allowed and not for 6.1.  Would have thought you could have used staging as the source were things commits not there yet?   Is develop to staging promotion turned off?

**Comment by daineAMD** [comment]
> LGTM. Yes I would ffwd as long as you are allowed and not for 6.1. Would have thought you could have used staging as the source were things commits not there yet? Is develop to staging promotion turned off?

I think the ff to staging is on. I just merged the last develop PR a few minutes ago so staging should be updated soon.

**Comment by amcamd** [comment]
For --ff-only merges usually I do it manually without a PR. If release-staging/rocm-rel-6.0 is only ahead (no commits behind) the branch this is coming from I think a "rebase and merge" may do the same thing.

**Comment by amcamd** [comment]
Looking at the commits in release-staging/rocm-rel-6.0 and the commits in this PR, a `rebase and merge` for this PR should be the same as --ff-only merging staging into release-staging/rocm-rel-6.0. Please `rebase and merge` this PR.

**Pull request merged**
