### PR TITLE
64-bit interface for blas1 _ex functions

### PR DESCRIPTION
**Pull request by daineAMD**

### CODE REVIEW

**Review by TorreZuk — APPROVED** [review]
LGTM, how many functions now in in hipBLAS?

**Comment by daineAMD** [comment]
> LGTM, how many functions now in in hipBLAS?

There appears to be 1624 functions exported in hipblas.h if that's what you're asking. I think around 300 more if all L3 and solver functions end up supported _64 interface. Removal/replacement of hipblasDatatype will remove ~30% of the functions.

**Comment by daineAMD** [comment]
Windows timed-out here too. I'll run manually as I'd like to see the blas1_ex functions pass there.

**Comment by daineAMD** [comment]
Local Windows tests passed so merging.

**Pull request merged**
