### PR TITLE
Address the readthedocs build failure

### PR DESCRIPTION
**Pull request by NaveenElumalaiAMD**
Summary of proposed changes:
- Address the hipBLAS documentation build error in readthedocs.

### CODE REVIEW

**Review by TorreZuk — APPROVED** [review]
LGTM should move to a system in the future where these are taken from a common repo, no need for each library to update these, nor for different libraries to have different styles ?(@saadrahim you know if this is already in the works)

**Comment by TorreZuk** [comment]
But you should wait to get Daine, Ruban and Andrew to approve as going to master.   Similarly hopefully all CI passes.

**Comment by saadrahim** [comment]
submodule link to a single file? unfortunately, that doesn't update automatically. rocm-cmake, not really cmake but we are interesting building docs?

**Comment by NaveenElumalaiAMD** [comment]
> But you should wait to get Daine, Ruban and Andrew to approve as going to master. Similarly hopefully all CI passes.

readthedocs build passed here for this PR:https://hipblas--472.org.readthedocs.build/en/472/

**Comment by NaveenElumalaiAMD** [comment]
The issue could be because of our outdated sphinx version in `docs/source/requirements.txt` as reported here: https://github.com/sphinx-doc/sphinx/issues/10291#issuecomment-1078101926 and this PR updates that.

**Review by rkamd — APPROVED** [review]
LGTM

**Review by bragadeesh — APPROVED** [review]
No need for CQE tests as this is doc change only

**Pull request merged**
