### PR TITLE
Add try and catch blocks to all functions

### PR DESCRIPTION
**Pull request by daineAMD**
Did a find and replace to add try{} and catch{} blocks for every function in hipblas.cpp (hcc and nvcc). Sorry for the large PR, but it seems to have worked after some cleanup.

### CODE REVIEW

**Review by TorreZuk — APPROVED** [review]
Excellent!  I assumed there were separate files for each function so it wouldn't have made any  sense to split up the work.

**Review by amcamd — APPROVED** [review]
LGTM, It is good to see the code quality incrementally improving by improvements like this preventing the leak of C++ exceptions from a C API.

**Comment by TorreZuk** [comment]
Probably worth a mention in the changelog as well.

**Comment by YvanMokwinski** [comment]
I was talking with Torre on this topic. This is something that needs to be standardized in {hip/roc}SPARSE too.

**Comment by cgmb** [comment]
I assume that rocBLAS may throw from the `*_template` methods? We adopted this try/catch in a few places in rocSOLVER where the possibility of throwing was obvious, but I suppose it should probably be done across-the-board. If there's anything we _know_ can't throw, we can mark it `noexcept`.

**Comment by YvanMokwinski** [comment]
May throw if using some class constructors ?  
In the rocSPARSE library the only thing that can throw is the C++ implementation of the handle (constructor), probably the same in rocBLAS? 

I remember Lee saying 'noexcept' is obsolete. I haven't verified.

**Comment by cgmb** [comment]
As far as I know, `noexcept` is not obsolete. However, it doesn't help in ensuring program correctness. It's a promise from the programmer to the compiler (and to other programmers) that a function will not throw. That sort of guarantee can sometimes be useful for optimization, but breaking that promise results in a call to `std::terminate`, so marking a function as `noexcept` requires great care.

**Comment by TorreZuk** [comment]
Daine is one of these failures that throws tested by the yaml or other unit test?   Sorry didn't have time to look for myself.

**Comment by daineAMD** [comment]
> Daine is one of these failures that throws tested by the yaml or other unit test? Sorry didn't have time to look for myself.

I didn't add any unit tests, I just did a manual test by removing an enum value from a conversion and trying to pass it in via hipblas-bench. I could add tests if desired.

**Comment by TorreZuk** [comment]
Could be a single call with a bad enum to convert that triggers the throw and catch.   Wouldn't say you have to test them all but verify that exception handling occurs as expected.  Or just sneak another case into a bad_args test that already exists.   Separate PR would be fine I would think.   If there isn't something like general_gtest.cpp from rocBLAS probably that might be worth adding for misc. tests.

**Comment by daineAMD** [comment]
I've added a quick test that calls gemv with a bad hipblasOperation_t and ensures that the new error code is returned, let me know what you think. I can add tests for all conversions later.

**Comment by TorreZuk** [comment]
Yes that looks good to me.     If something goes awry with exception handling that should catch it  :-)

**Pull request merged**
