### PR TITLE
ROCm 4.2 merge staging into master

### PR DESCRIPTION
**Pull request by daineAMD**

### CODE REVIEW

**Review by TorreZuk — APPROVED** [review]
LGTM

**Review by amcamd — APPROVED** [review]

**Comment by daineAMD** [comment]
Will wait for rocSOLVER to be ready on CI to kick off another run of CI here, will merge after it passes.

**Comment by daineAMD** [comment]
It looks like rocSOLVER build failed because it was picking up the wrong rocBLAS version. rocBLAS on master is still running on CI. I will merge this PR at ~6:30pm MT (in about half an hour) unless I hear otherwise since hipBLAS has been running fine on develop.

**Comment by amcamd** [comment]
Hi Daine, Can you go ahead and merge. It will take hours for rocSOLVER CI to complete. I expect that will be about 11/10/9 central/mountain/pacific. I think it is best to merge now.

**Pull request merged**
