### PR TITLE
Allow debug builds in jenkins

### PR DESCRIPTION
**Pull request by daineAMD**

### CODE REVIEW

**Review by TorreZuk — APPROVED** [review]
I was just thinking of adding this exact change :-)

**Comment by TorreZuk** [comment]
I can make debug packages locally, maybe look at rocblas groovy for hints.   I would think maybe we should remove the debug suffix unless you heard otherwise?  We don't use them on rocblas do we?  
DEBUG_POSTFIX I am referring to as suffix

**Comment by daineAMD** [comment]
We don't seem to have them in rocblas as far as I can tell. I don't think anyone tests our debug builds as far as I know.
I've removed DEBUG_POSTFIX in my last commit. Maybe it should be it's own PR though, let me know what you think.

**Comment by TorreZuk** [comment]
Well the testing can run the same executable so fine to leave it in the POSTFIX change in here.  If someone needed it back it is a couple lines.

**Pull request merged**
