### PR TITLE
cmake: don't set CMAKE_C_COMPILER, as hipBLAS is a CXX project

### PR DESCRIPTION
**Pull request by evetsso**
See https://github.com/ROCm/rocPRIM/pull/567 for a description of the errors solved by this change.

### CODE REVIEW

**Review by daineAMD — APPROVED** [review]
LGTM as long as CI passes, looks like cuda CI failed due to docker issues.
I can merge back into develop afterward.

**Review by TorreZuk — APPROVED** [review]
LGTM

**Comment by daineAMD** [comment]
I think we'll need the change from https://github.com/ROCm/hipBLAS/pull/873/commits/5f23b35283be7110d4a82d7253f82bc0a0202851 to go into release-staging/rocm-rel-6.2 as well to get static builds to pass, so I expect static CI to fail here.

I'm ok if you go ahead and merge this one even with the static failure and I can create a PR afterwards to include that change. Otherwise you can make that change here too if you want.

**Comment by TorreZuk** [comment]
Will re-run with noSOLVER to see if at least something can build.

**Comment by evetsso** [comment]
> Will re-run with noSOLVER to see if at least something can build.

Thanks.  FWIW, I've been able to manually build with my own rocSOLVER.

**Comment by TorreZuk** [comment]
Re-run in CI passed on one OS without solver (non static) so IMO you are safe to merge.

**Comment by evetsso** [comment]
Oh.. seems I don't have permission to merge.  @TorreZuk , @daineAMD I think one of you can probably do it?

**Pull request merged**
