### PR TITLE
Add rocSPARSE dependency download to CI runs

### PR DESCRIPTION
**Pull request by eidenyoshida**
rocSOLVER now depends on rocSPARSE

### CODE REVIEW

**Review by TorreZuk — APPROVED** [review]
LGTM if tests pass

**Review by daineAMD — COMMENTED** [review]
Identical to #587 right?

**Comment by eidenyoshida** [comment]
I should have checked, my bad. We need to merge either one because it's blocking hipBLASLt.

**Comment by TorreZuk** [comment]
Strange, if this relates to hipBLASLt I thought they removed their hipBLAS dependency (they mentioned that in the hipBLASLt failure ticket).  I'll see if I can find that.

**Comment by TorreZuk** [comment]
hipBLASLt commit 0412369bdcddc258cb88dd874beaf6c647486889 claims to remove the dependency on hipBLAS.

**Pull request closed without merging**
