### PR TITLE
Clients CMake cleanup

### PR DESCRIPTION
**Pull request by cgmb**
When putting together https://github.com/spack/spack/pull/27074, I noticed that hipblas-test can end up missing some blas symbols. I patched it in Spack, but I figured I should probably make the change here, too.

While I was at it, I figured I'd make a couple other changes to clean up the clients build:

- Simplify CMake using REQUIRED
- Cleanup GTest in clients
- Ensure that blas is linked
- Consolidate hipblas-bench target properties

### CODE REVIEW

**Review by TorreZuk — APPROVED** [review]
LGTM if all tests pass, windows you have to go check as the link I don't see.

**Comment by cgmb** [comment]
Unless I'm missing something, it looks like GTest 1.11.0 did break something. Though, perhaps this is really more like an error in our tests that it has uncovered?

```
[0;32m[----------] [m14 tests from GoogleTestVerification
[0;32m[ RUN      ] [mGoogleTestVerification.UninstantiatedParameterizedTestSuite<gbmv_gtest_batched>
../../../../clients/gtest/gbmv_batched_gtest.cpp:197: Failure
Parameterized test suite gbmv_gtest_batched is instantiated via INSTANTIATE_TEST_SUITE_P, but no tests are defined via TEST_P . No test cases will run.

Ideally, INSTANTIATE_TEST_SUITE_P should only ever be invoked from code that always depend on code that provides TEST_P. Failing to do so is often an indication of dead code, e.g. the last TEST_P was removed but the rest got left behind.

To suppress this error for this test suite, insert the following line (in a non-header) in the namespace it is defined in:

GTEST_ALLOW_UNINSTANTIATED_PARAMETERIZED_TEST(gbmv_gtest_batched);
```

**Comment by TorreZuk** [comment]
Yes commented on this in the channel, not your PR but the CI gtest change.  Discuss further there.

**Comment by cgmb** [comment]
The Windows CI is using outdated versions of rocBLAS and rocSOLVER, but it appears to work.
http://mlsejenkinsvm.amd.com/blue/organizations/jenkins/Math%20Libraries%2FhipBLAS/detail/PR-409/4/pipeline

**Review by daineAMD — APPROVED** [review]

**Pull request merged**
