### PR TITLE
Rename 'aux' dirs to 'auxil'

### PR DESCRIPTION
**Pull request by daineAMD**
Windows doesn't like files/folders named 'aux', see https://learn.microsoft.com/en-ca/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#win32-file-namespaces

### CODE REVIEW

**Review by TorreZuk — APPROVED** [review]
Okay but I think I don't like auxil either, not sure why though :-)

**Comment by daineAMD** [comment]
> Okay but I think I don't like auxil either, not sure why though :-)

Any preference on another name? 'misc', 'auxiliary', 'other', 'blas_aux', 'blas0'? We don't have these folders in rocblas

**Comment by TorreZuk** [comment]
> > Okay but I think I don't like auxil either, not sure why though :-)
> 
> Any preference on another name? 'misc', 'auxiliary', 'other', 'blas_aux', 'blas0'? We don't have these folders in rocblas

It is fine.   Etymology fits it

**Review by amcamd — APPROVED** [review]
good thing aux and auxil occur in auxiliary and not any other word I can find.

**Comment by TorreZuk** [comment]
I think that it built may be enough results to merge.  The test looks like some connection failure so can just review the next develop test run

**Pull request merged**
