### PR TITLE
Updating changelog

### PR DESCRIPTION
**Pull request by daineAMD**
Not many changes in hipBLAS this cycle, but thought there should be something there.

### CODE REVIEW

**Review by TorreZuk — APPROVED** [review]
You could add if you want more?
#Fixed 
Avoid large offset overflow for gemv and hemv in hiblas-test

**Comment by amcamd** [comment]
Could you also add:

Added hipblas-bench with support for syrkx

**Comment by daineAMD** [comment]
@amcamd That's what I was trying to imply with "Added more support for hipblas-bench". There were a handful of functions added, I can list them all separately if desired, although I haven't done that in the past releases.

**Comment by amcamd** [comment]
@daineAMD, sorry I should have seen your comment covers syrkx changes. Go ahead with your present PR, no need to list functions separately.

**Review by amcamd — APPROVED** [review]
LGTM

**Pull request merged**
