### PR TITLE
force gfortran &  link bench & test for sanitizer

### PR DESCRIPTION
**Pull request by TorreZuk**
* minimal fixes for address-sanitizer 
* forces lapack deps build to use gfortran

### CODE REVIEW

**Review by daineAMD — APPROVED** [review]
LGTM, CI is picking up an older rocSOLVER (3652c6e) that doesn't have Andrew's fixes (in 7f393d6) yet. It looks like rocSOLVER on master has been passing (the last one passed a couple of hours ago) so not sure why it isn't being picked up.

**Comment by TorreZuk** [comment]
Thanks Daine, @eidenyoshida master will pick up master artifacts right?   I'll just re-run the job for this.

**Comment by eidenyoshida** [comment]
Yes PRs to master branch should pick up master branch artifacts from rocblas ci

**Comment by eidenyoshida** [comment]
accidentally closed pr, sorry

**Pull request merged**
