### PR TITLE
Trsm fix

### PR DESCRIPTION
**Pull request by daineAMD**
Should fix failing trsm tests.

### CODE REVIEW

**Review by leekillough — APPROVED** [review]
LGTM as long as CI passes

**Comment by leekillough** [comment]
```
Could not find compiler set in environment variable CXX:

  clang++.
```

**Review by amcamd — APPROVED** [review]
LGTM

**Comment by daineAMD** [comment]
A packaging error (looks like the .deb file already exists on the CI machine) and a MultiCompiler error (can't compile on clang++ because it can't find it). Both unrelated and don't seem critical, so merging, and will continue on with the 3.9 merge.

**Pull request merged**
