### PR TITLE
Adding cmath include for cs9

### PR DESCRIPTION
**Pull request by daineAMD**

### CODE REVIEW

**Comment by daineAMD** [comment]
Since I'm not seeing PRs being ran on the failing CI, in docker container given in the ticket all tests passed:

[----------] Global test environment tear-down
[==========] 296478 tests from 87 test suites ran. (781996 ms total)
[  PASSED  ] 296478 tests

**Review by TorreZuk — APPROVED** [review]
What math function is this for?  Check windows build too, CI may have other issues so may require manual build.

**Comment by daineAMD** [comment]
> What math function is this for? Check windows build too, CI may have other issues so may require manual build.

[std::abs](https://github.com/ROCmSoftwarePlatform/hipBLAS/blob/develop/clients/include/device_batch_vector.hpp#L65)

**Comment by daineAMD** [comment]
Looks like Windows build is OK on CI, but tests fail because it can't find hipinfo.exe, seeing the same problem in [rocBLAS Windows CI](http://mlsejenkinsvm.amd.com/blue/organizations/jenkins/ROCmMathLib%2FrocBLAS/detail/develop/140/pipeline/428).

**Pull request merged**
