### PR TITLE
merge staging b1087b1 into master with GO from CQE

### PR DESCRIPTION
**Pull request by daineAMD**

### CODE REVIEW

**Review by amcamd — APPROVED** [review]
LGTM

**Review by TorreZuk — APPROVED** [review]
LGTM but this is for 4.4 right, just a missed 4.3 change note I assume

**Comment by daineAMD** [comment]
> LGTM but this is for 4.4 right, just a missed 4.3 change note I assume

Do you mean adding a 4.4 section in CHANGELOG? Yeah I can make sure to add that in my next PR to develop.

**Comment by TorreZuk** [comment]
No I just meant shouldn't the comment on 4.3 rel already be in master as this now for 4.4.  Sure 4.4 section can come later.

**Comment by daineAMD** [comment]
> No I just meant shouldn't the comment on 4.3 rel already be in master as this now for 4.4. Sure 4.4 section can come later.

Ah, yeah looks like that PR didn't make it into 4.3 for some reason, will have to move that changelog comment to rel 4.4

**Pull request merged**
