### PR TITLE
Add hipblas-common as dep for Jenkins

### PR DESCRIPTION
**Pull request by samjwu**
Summary of proposed changes:
- Use hipblas-common as dependency for Jenkins jobs
- Affected jobs includes
  - multicompiler
  - precheckin
  - precheckin cuda
  - static

### CODE REVIEW

**Comment by samjwu** [comment]
precheckin-cuda failure due to missing image
static failure due to missing dep: hip-runtime-amd

**Comment by samjwu** [comment]
hipblas-common repo: https://github.com/ROCm/hipBLAS-common

**Review by eidenyoshida — APPROVED** [review]

**Review by TorreZuk — APPROVED** [review]
LGTM if available for all pipelines

**Comment by daineAMD** [comment]
Is the cuda failure caused by this? http://math-ci.amd.com/job/cuda-temporary/job/precheckin-cuda/job/hipBLAS/job/PR-868/7/pipeline-console/?selected-node=188

**Pull request merged**
