### PR TITLE
ROCm 4.1 merge staging into master

### PR DESCRIPTION
**Pull request by daineAMD**

### CODE REVIEW

**Review by TorreZuk — COMMENTED** [review]
Is rocSOLVER not available yet?   NEW_MINIMUM_ROCSOLVER_VERSION didn't change.

**Review by amcamd — APPROVED** [review]
LGTM

**Review by jzuniga-amd — APPROVED** [review]
Yes, rocSOLVER version did not change. It is still 3.11 for ROCm4.1

**Comment by cgmb** [comment]
@TorreZuk: To clarify a little, we'd planned to ship rocSOLVER 3.11 with ROCm 4.0, but it was delayed to ROCm 4.1.

**Pull request merged**
